[theme]
base = "light"
primaryColor = "#6E5A4D"
backgroundColor = "#F7F0E8"
secondaryBackgroundColor = "#FFF9F2"
textColor = "#40352F"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[client]
toolbarMode = "minimal"
